version: '2'
services:
  server:
    build: server/.
    ports:
      - "80:80"
    volumes:
      - ..:/var/www/html/
    depends_on:
      - database
  database:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

